In [1]:
import pandas as pd
import numpy as np
import quandl
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [2]:
df = quandl.get("WIKI/FB")

In [3]:
df.head()

Open   High    Low    Close       Volume  Ex-Dividend  \
Date                                                                 
2012-05-18  42.05  45.00  38.00  38.2318  573576400.0          0.0   
2012-05-21  36.53  36.66  33.00  34.0300  168192700.0          0.0   
2012-05-22  32.61  33.59  30.94  31.0000  101786600.0          0.0   
2012-05-23  31.37  32.50  31.36  32.0000   73600000.0          0.0   
2012-05-24  32.95  33.21  31.77  33.0300   50237200.0          0.0   

            Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  \
Date                                                                  
2012-05-18          1.0      42.05      45.00     38.00     38.2318   
2012-05-21          1.0      36.53      36.66     33.00     34.0300   
2012-05-22          1.0      32.61      33.59     30.94     31.0000   
2012-05-23          1.0      31.37      32.50     31.36     32.0000   
2012-05-24          1.0      32.95      33.21     31.77     33.0300   

            Adj. Volume  
Date                     
2012-05-18  573576400.0  
2012-05-21  168192700.0  
2012-05-22  101786600.0  
2012-05-23   73600000.0  
2012-05-24   50237200.0

In [4]:
df = df[['Adj. Close']]

In [5]:
df.head()

Adj. Close
Date                  
2012-05-18     38.2318
2012-05-21     34.0300
2012-05-22     31.0000
2012-05-23     32.0000
2012-05-24     33.0300

In [10]:
df['prediction'] = df[['Adj. Close']].shift(-30)
df.head()

Adj. Close  prediction
Date                              
2012-05-18     38.2318      30.771
2012-05-21     34.0300      31.200
2012-05-22     31.0000      31.470
2012-05-23     32.0000      31.730
2012-05-24     33.0300      32.170

In [11]:
df.shape

(1472, 2)

In [12]:
df.iloc[1471]

Adj. Close    152.19
prediction       NaN
Name: 2018-03-27 00:00:00, dtype: float64

In [13]:
X = np.array(df.drop(['prediction'], 1))

In [14]:
X = X[:-30]

In [17]:
X

array([[ 38.2318],
       [ 34.03  ],
       [ 31.    ],
       ...,
       [171.5499],
       [175.98  ],
       [176.41  ]])

In [18]:
y = np.array(df['prediction'])

In [19]:
y[-1]

nan

In [20]:
y = y[:-30]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [23]:
svr_rbf = SVR(kernel = 'rbf', C = 1e3, gamma = 0.1)
svr_rbf.fit(X_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [26]:
svr_rbf.score(X_test, y_test)

0.9836230489839954

In [36]:
print(svr_rbf.predict(X_test)[:5])
print(y_test[:5])

[115.57662531 132.57184041  50.66861327  59.51875616 174.62081783]
[117.58 117.77  43.6   61.36 179.04]


In [32]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(svr_rbf.predict(X_test), y_test)

4.6257192426117

In [38]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [39]:
lr.score(X_test, y_test)


0.9804490251952244

In [43]:
x_forecast = np.array(df.drop(['prediction'], 1))[-30:]

In [44]:
print(x_forecast)

[[173.15]
 [179.52]
 [179.96]
 [177.36]
 [176.01]
 [177.91]
 [178.99]
 [183.29]
 [184.93]
 [181.46]
 [178.32]
 [175.94]
 [176.62]
 [180.4 ]
 [179.78]
 [183.71]
 [182.34]
 [185.23]
 [184.76]
 [181.88]
 [184.19]
 [183.86]
 [185.09]
 [172.56]
 [168.15]
 [169.39]
 [164.89]
 [159.39]
 [160.06]
 [152.19]]


In [45]:
lr.predict(x_forecast)

array([177.17375321, 183.62383112, 184.06936241, 181.43667754,
       180.06970656, 181.99359165, 183.08716844, 187.44122418,
       189.10184078, 185.58821906, 182.4087458 , 179.99882658,
       180.68737493, 184.51489369, 183.88709961, 187.86650404,
       186.47928163, 189.40561211, 188.92970369, 186.01349892,
       188.35253817, 188.0183897 , 189.26385216, 176.57633626,
       172.1108977 , 173.36648587, 168.80991591, 163.24077485,
       163.91919749, 155.95026292])

In [46]:
svr_rbf.predict(x_forecast)

array([174.53317122, 178.32704774, 178.39359553, 176.85306591,
       176.83303902, 177.58535847, 178.48992596, 185.80817156,
       179.134706  , 184.20380522, 178.1441061 , 176.84747258,
       176.60464121, 179.14198831, 178.30810528, 183.49749869,
       187.78048454, 179.38729808, 179.24511663, 186.39109803,
       180.94509711, 182.64426541, 179.20145747, 175.48904579,
       171.14514893, 172.23852981, 172.27003793, 167.56647772,
       166.26556798, 162.44393742])